/**
 * Goal-only run with steps generated by the LLM (no steps defined by you).
 * Set OPENAI_API_KEY then: npm run example:goal-driven-llm
 * Optional: pass a goal as argv[2], e.g. npm run example:goal-driven-llm -- "Explain recursion in 2 steps"
 */

import { createGoalDrivenAgent } from "../src/quickStart.js";

const runner = createGoalDrivenAgent({
  provider: "openai",
  useLLMPlanner: true,
  llmPlannerOptions: { maxSteps: 5, planHint: "Use 2–4 clear steps." },
});

const goal =
  process.argv[2] ??
  "Explain what an API is in three short steps: 1) definition, 2) why it matters, 3) one example.";

console.log("Goal:", goal);
console.log("Running (LLM will define the steps)...\n");

const run = await runner.run({ goal, context: {} });

console.log("Plan steps:", run.plan.steps.length);
run.plan.steps.forEach((s, i) => {
  console.log(`  ${i + 1}. ${s.id}: ${s.objective.slice(0, 60)}...`);
});
console.log("\nOutputs:", Object.keys(run.outputs ?? {}));
const lastOutputKey = run.plan.steps[run.plan.steps.length - 1]?.outputs?.[0];
if (lastOutputKey && run.outputs?.[lastOutputKey]) {
  console.log("\nFinal answer:\n", run.outputs[lastOutputKey]);
}
